[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "idrive-backup"
version = "0.0.1"
dependencies = [
    "pytest",
    "requests",
    'importlib-metadata; python_version>="3.5"',
]
