[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "idrive-backup"
version = "0.0.1"
dependencies = [
    "pytest",
    "requests",
    "importlib-metadata",
]

[project.scripts]
idrive-query = "idrive.query:main"
