#!/usr/bin/env python

import argparse
import datetime
from getpass import getpass
import logging
import os
import sys

from idrive import (
    db_init,
    db_has_folder,
    db_insert_folder,
    db_fetch_next_folder,
    db_cursor,
    db_cursor_insert_folder,
    db_cursor_insert_file,
    db_cursor_update_folder_size,
    db_cursor_update_folder_status,
    FileStatus,
    log,
    idrive_get_host,
    idrive_login,
    idrive_browseFolder,
)


def getuser(prompt):
    sys.stdout.write(prompt)
    sys.stdout.flush()
    return input()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-uid', '--user-id', type=str, help='IDrive login user ID.')
    parser.add_argument('-pwd', '--password', type=str, help='IDrive login password.')
    parser.add_argument('-dev', '--device-id', type=str, help='IDrive device ID.')
    parser.add_argument('-db', '--db-name', type=str, help='SQLite database name.')
    parser.add_argument('-v', '--verbose', action='store_true', help='Enable verbosity.')
    args = parser.parse_args()

    if args.verbose:
        logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

    uid = args.user_id or getuser(prompt="IDrive User ID: ")
    pwd = args.password or getpass(prompt="IDrive Password: ")
    device_id = args.device_id
    assert uid and pwd
    assert device_id, "Device ID is required."

    # setup
    host = idrive_get_host()
    db_init(args.db_name, host=host, device_id=device_id)
    idrive_login(uid, pwd)
    root_folder = '/'
    if not db_has_folder(root_folder, host=host, device_id=device_id):
        db_insert_folder(root_folder, host=host, device_id=device_id)

    # add filesystem folders and files to database
    while True:
        # get a starting folder for search:
        # query db for a folder with no filename and defaul status limit 1
        root_folder = db_fetch_next_folder(host=host, device_id=device_id)
        if not root_folder:
            break

        cursor = db_cursor(host=host, device_id=device_id)

        # list the folder
        try:
            files = idrive_browseFolder(device_id, root_folder)
        except:
            db_cursor_update_folder_status(cursor, root_folder, FileStatus.ERROR, host=host, device_id=device_id)
            cursor.connection.commit()
            continue

        # add all files and subfolders to database
        for file_info in files:
            filename, is_dir = file_info['name'], file_info['is_dir']
            if is_dir:
                folder = os.path.join(root_folder, filename) + '/'
                db_cursor_insert_folder(cursor, folder, host=host, device_id=device_id)
            else:
                size, lmd = int(file_info['size']), file_info['lmd']
                mtime = int(round(datetime.datetime.strptime(lmd, '%Y/%m/%d %H:%M:%S').replace(tzinfo=datetime.timezone.utc).timestamp()))
                db_cursor_insert_file(cursor, root_folder, filename, host=host, device_id=device_id, size=size, mtime=mtime)

        # update the size of the folder in the database with the number of files/folders
        size = len(files)
        db_cursor_update_folder_size(cursor, root_folder, size, host=host, device_id=device_id)
        db_cursor_update_folder_status(cursor, root_folder, FileStatus.SCANNED, host=host, device_id=device_id)

        # commit
        cursor.connection.commit()

    log.info("Done ingesting!")


if __name__ == '__main__':
    os.nice(19)
    main()
